import { Router } from 'express';
import authRoutes from './auth';
import userRoutes from './users';
import roleRoutes from './roles';
import permissionRoutes from './permissions';
import dispatchScheduleRoutes from './dispatchSchedules';
import weightAdjustmentRoutes from './weightAdjustments';
import deliveryScheduleRoutes from './deliverySchedule';
import customerRoutes from './customers';
import driverInvoiceRoutes from './driverInvoices';
import deliveryDataRoutes from './deliveryData';
import accountantInvoiceRoutes from './accountantInvoices';
import vehicleRoutes from './vehicles';
import innerCityCustomerRoutes from './innerCityCustomers';
import promoItemRoutes from './promoItems';
import supplierRoutes from './suppliers';
import reconcileJobRoutes from './reconcileJobs';
import auditLogRoutes from './auditLogs';
import fuelRecordRoutes from './fuelRecords';
import vehicleInspectionRoutes from './vehicleInspections';
import vehicleOilChangeRoutes from './vehicleOilChanges';
import vehicleInsuranceRoutes from './vehicleInsurances';
import vehicleRepairRoutes from './vehicleRepairs';
import routePricingRoutes from './routePricing';
import dashboardRoutes from './dashboard';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/dispatch-schedules', dispatchScheduleRoutes);
router.use('/weight-adjustments', weightAdjustmentRoutes);
router.use('/delivery-schedules', deliveryScheduleRoutes);
router.use('/customers', customerRoutes);
router.use('/driver-invoices', driverInvoiceRoutes);
router.use('/delivery-data', deliveryDataRoutes);
router.use('/accountant-invoices', accountantInvoiceRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/inner-city-customers', innerCityCustomerRoutes);
router.use('/promo-items', promoItemRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/reconcile-jobs', reconcileJobRoutes);
router.use('/logs', auditLogRoutes);
router.use('/fuel-records', fuelRecordRoutes);
router.use('/vehicle-inspections', vehicleInspectionRoutes);
router.use('/vehicle-oil-changes', vehicleOilChangeRoutes);
router.use('/vehicle-insurances', vehicleInsuranceRoutes);
router.use('/vehicle-repairs', vehicleRepairRoutes);
router.use('/route-pricing', routePricingRoutes);
router.use('/dashboard', dashboardRoutes);

export default router;
